development:
  adapter: postgresql
  database: kitchen_recipes_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kitchen_recipes_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql